# Docker registry
docker_registry_server: 
docker_registry_username: 
docker_registry_password:
docker_registry_email: 
docker_secret_name: 

# Env secret
env_secret_name:
env_secret_file: .env

# Argo CD repository secret
repo_secret_name:
namespace:
repo_url:
repo_username:
repo_token:

# k3s slave node
k3s_master_token: 
k3s_master_ip: 